### ISSUE TITLE
[Suggestion] Reward Slots

### ISSUE THREAD

**Issue by elkoyofficial** [HibiscusMC/HMCRewards#1]
Hi, could there be a way where we can select what slots are used for rewards instead of the current method?

> list:
>   from: 19
>   to: 25

Proposed:

Slots:
     - 1
     - 2
     - 3
     - 4

This will make our menus more customizable.
Thanks!

**Comment by yusshu** [comment]
Done! Example:
![image](https://github.com/HibiscusMC/HMCRewards/assets/45738853/3827dc81-b452-424b-bfdc-8c91344f5191)
![2024-05-06_15 01 59](https://github.com/HibiscusMC/HMCRewards/assets/45738853/9ef86486-0791-4075-99bb-76264bb331f2)
Will be available in the next update 👍🏽

**Comment by elkoyofficial** [comment]
Awesome, thank you!
